import type { Content, Story } from '../types';

export const mockContents: Content[] = [
  // Movies
  {
    id: 'm1',
    title: 'The Dark Horizon',
    subtitle: 'Sci-Fi Thriller • 2025',
    iconUrl: 'https://picsum.photos/seed/movie1/100/100',
    imageUrl: 'https://picsum.photos/seed/movie1bg/800/600',
    price: 4.99,
    rating: 4.5,
    ratingCount: 28500,
    category: 'Sci-Fi',
    contentType: 'MOVIE',
    genre: ['Sci-Fi', 'Thriller'],
    description: 'A mind-bending journey through space and time.',
  },
  {
    id: 'm2',
    title: 'Laugh Track',
    subtitle: 'Comedy • 2025',
    iconUrl: 'https://picsum.photos/seed/movie2/100/100',
    imageUrl: 'https://picsum.photos/seed/movie2bg/800/600',
    price: 3.99,
    rating: 4.2,
    ratingCount: 15200,
    category: 'Comedy',
    contentType: 'MOVIE',
    genre: ['Comedy'],
  },
  {
    id: 'm3',
    title: 'Quantum Shift',
    subtitle: 'Action Adventure',
    iconUrl: 'https://picsum.photos/seed/movie3/100/100',
    imageUrl: 'https://picsum.photos/seed/movie3bg/800/600',
    price: 5.99,
    rating: 4.8,
    ratingCount: 42100,
    category: 'Action',
    contentType: 'MOVIE',
    genre: ['Action', 'Adventure'],
  },
  {
    id: 'm4',
    title: 'The Last Symphony',
    subtitle: 'Drama • Biography',
    iconUrl: 'https://picsum.photos/seed/movie4/100/100',
    imageUrl: 'https://picsum.photos/seed/movie4bg/800/600',
    price: 4.99,
    rating: 4.6,
    ratingCount: 18300,
    category: 'Drama',
    contentType: 'MOVIE',
    genre: ['Drama', 'Biography'],
  },
  {
    id: 'm5',
    title: 'Neon Nights',
    subtitle: 'Cyberpunk Thriller',
    iconUrl: 'https://picsum.photos/seed/movie5/100/100',
    imageUrl: 'https://picsum.photos/seed/movie5bg/800/600',
    price: 3.99,
    rating: 4.3,
    ratingCount: 9700,
    category: 'Sci-Fi',
    contentType: 'MOVIE',
    genre: ['Sci-Fi', 'Cyberpunk'],
  },

  // Books
  {
    id: 'b1',
    title: 'The Startup Code',
    subtitle: 'Business & Technology',
    iconUrl: 'https://picsum.photos/seed/book1/100/100',
    imageUrl: 'https://picsum.photos/seed/book1bg/800/600',
    price: 9.99,
    rating: 4.7,
    ratingCount: 12500,
    category: 'Business',
    contentType: 'BOOK',
    genre: ['Business', 'Technology'],
    description: 'Master the art of building successful startups.',
  },
  {
    id: 'b2',
    title: 'Echoes of Empire',
    subtitle: 'Historical Fiction',
    iconUrl: 'https://picsum.photos/seed/book2/100/100',
    imageUrl: 'https://picsum.photos/seed/book2bg/800/600',
    price: 7.99,
    rating: 4.4,
    ratingCount: 8300,
    category: 'Fiction',
    contentType: 'BOOK',
    genre: ['Fiction', 'Historical'],
  },
  {
    id: 'b3',
    title: 'Mind Over Machines',
    subtitle: 'AI & The Future',
    iconUrl: 'https://picsum.photos/seed/book3/100/100',
    imageUrl: 'https://picsum.photos/seed/book3bg/800/600',
    price: 12.99,
    rating: 4.9,
    ratingCount: 21500,
    category: 'Technology',
    contentType: 'BOOK',
    genre: ['Technology', 'Science'],
  },
  {
    id: 'b4',
    title: 'The Silent Garden',
    subtitle: 'Literary Fiction',
    iconUrl: 'https://picsum.photos/seed/book4/100/100',
    price: 6.99,
    rating: 4.5,
    ratingCount: 11200,
    category: 'Fiction',
    contentType: 'BOOK',
    genre: ['Fiction', 'Literary'],
  },
  {
    id: 'b5',
    title: 'Cook Smart',
    subtitle: 'Healthy Recipes',
    iconUrl: 'https://picsum.photos/seed/book5/100/100',
    price: 5.99,
    rating: 4.3,
    ratingCount: 6400,
    category: 'Cooking',
    contentType: 'BOOK',
    genre: ['Cooking', 'Health'],
  },

  // Apps
  {
    id: 'a1',
    title: 'PixelForge Pro',
    subtitle: 'Photo Editor',
    iconUrl: 'https://picsum.photos/seed/app1/100/100',
    rating: 4.6,
    ratingCount: 34200,
    category: 'Photography',
    contentType: 'APP',
    genre: ['Photography'],
  },
  {
    id: 'a2',
    title: 'ZenSpace',
    subtitle: 'Meditation & Focus',
    iconUrl: 'https://picsum.photos/seed/app2/100/100',
    rating: 4.8,
    ratingCount: 98700,
    category: 'Health & Fitness',
    contentType: 'APP',
    genre: ['Health', 'Wellness'],
  },
  {
    id: 'a3',
    title: 'Shadow Legends',
    subtitle: 'Epic RPG Adventure',
    iconUrl: 'https://picsum.photos/seed/app3/100/100',
    imageUrl: 'https://picsum.photos/seed/app3bg/800/600',
    rating: 4.4,
    ratingCount: 52300,
    category: 'Games',
    contentType: 'APP',
    genre: ['Games', 'RPG'],
  },
  {
    id: 'a4',
    title: 'TaskFlow',
    subtitle: 'Project Management',
    iconUrl: 'https://picsum.photos/seed/app4/100/100',
    price: 4.99,
    rating: 4.5,
    ratingCount: 18600,
    category: 'Productivity',
    contentType: 'APP',
    genre: ['Productivity'],
  },
  {
    id: 'a5',
    title: 'Star Racers',
    subtitle: 'Multiplayer Racing',
    iconUrl: 'https://picsum.photos/seed/app5/100/100',
    imageUrl: 'https://picsum.photos/seed/app5bg/800/600',
    rating: 4.3,
    ratingCount: 28900,
    category: 'Games',
    contentType: 'APP',
    genre: ['Games', 'Racing'],
  },
  {
    id: 'a6',
    title: 'LearnLang',
    subtitle: 'Language Learning',
    iconUrl: 'https://picsum.photos/seed/app6/100/100',
    rating: 4.7,
    ratingCount: 76500,
    category: 'Education',
    contentType: 'APP',
    genre: ['Education'],
  },
];

export const mockStories: Story[] = [
  {
    id: 's1',
    title: 'Top-Selling Movies',
    subtitle: 'The biggest blockbusters this week.',
    legend: 'Collection',
    imageUrl: 'https://picsum.photos/seed/story1/800/600',
    backgroundColor: '#1a237e',
    contents: [mockContents[0], mockContents[2], mockContents[3]],
    date: new Date().toISOString(),
  },
  {
    id: 's2',
    title: 'The Dark Horizon',
    legend: 'Movie of the Week',
    imageUrl: 'https://picsum.photos/seed/story2/800/600',
    backgroundColor: '#0d47a1',
    hero: true,
    content: mockContents[0],
    date: new Date().toISOString(),
  },
  {
    id: 's3',
    title: 'Top-selling eBooks',
    subtitle: 'Books everyone is reading right now.',
    legend: 'Editors\' Choice',
    imageUrl: 'https://picsum.photos/seed/story3/800/600',
    backgroundColor: '#1b5e20',
    content: mockContents[6],
    contents: [mockContents[5], mockContents[7], mockContents[8]],
    date: new Date().toISOString(),
  },
  {
    id: 's4',
    title: 'Shadow Legends',
    legend: 'Game of the Week',
    imageUrl: 'https://picsum.photos/seed/story4/800/600',
    backgroundColor: '#4a148c',
    hero: true,
    content: mockContents[12],
    date: new Date().toISOString(),
  },
  {
    id: 's5',
    title: 'New & Updated Games',
    subtitle: 'Fresh adventures for your phone.',
    legend: 'Collection',
    imageUrl: 'https://picsum.photos/seed/story5/800/600',
    backgroundColor: '#e65100',
    contents: [mockContents[12], mockContents[14]],
    date: new Date().toISOString(),
  },
];

export const homeLipsum = [
  'Discover hand-picked recommendations across movies, books, and apps. Our editors curate the best content every day to help you find your next favorite.',
  'From blockbuster movies to page-turning books and addictive games — the StoryBox has something for everyone. Browse collections tailored to your interests.',
  'Stay up to date with the latest releases and top charts. Whether you\'re looking for entertainment, knowledge, or productivity tools, we\'ve got you covered.',
  'Personalized picks, curated collections, and editor favorites — all in one place. Start exploring and find content you\'ll love.',
];
